### ISSUE TITLE
Refactor FFI to be effectful

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/purescript-sodium#10]
Started but needs continuation and more thought... might be that the entire API needs to be run via Effects since really there is mutation happening on the JS side, even if just local state within the classes

**Comment by dakom** [comment]
Deciding not to do this for now... creation genuinely needs to be in an Effect, as does `sample`/`listen`.... but everything else should be referentially transparent from that point in... I think!

@clinuxrulz what do you think?

**Comment by dakom** [comment]
Closing for now... on one foot, imagining that the compiler _does_ try to optimise - I think something like the following pseudocode would still be okay:

```
c1 = new Cell()
c2 = c1.map(foo);
c3 = c1.map(foo); // return c2 instead of a new instantiation

```

**Comment by clinuxrulz** [comment]
Reactive Banana on hackage is probably a good guide on where to use effects and where to be pure. Seek it out for inspiration.
