### ISSUE TITLE
execute function

### ISSUE THREAD

**Issue by clinuxrulz** [SodiumFRP/purescript-sodium#15]
```execute :: Stream (Effect a) -> Stream a```

This one is important for a FRP library in a pure functional programming language. You will not see this one in other languages like Typescript or Java, because we can just do side effects in ```map```. It can be implemented via Typescript's  Stream map under the hood.

It is one of the functions listed in the denotational semantics, promise I did not just make it up. :wink:

**Comment by dakom** [comment]
Isn't this equivilent to mapping the stream with [unsafePerformEffect](https://pursuit.purescript.org/packages/purescript-effect/2.0.0/docs/Effect.Unsafe#v:unsafePerformEffect)?

In other words:

```
execute :: forall a. Stream (Effect a) -> Stream a
execute = map unsafePerformEffect
```

**Comment by clinuxrulz** [comment]
Yes. That looks OK.

**Comment by dakom** [comment]
Maybe we can have a recipe's page on the wiki here, and add this there? Or do you think that because it's in the semantics doc it should be a core primitive?

Feels kinda strange to add something that's just a one-liner map - but I trust your judgement here... I've never used the function myself (only used the Typescript implementation)

**Comment by clinuxrulz** [comment]
Should definitely be a core primitive. Because it is a safe thing to do in sodium. And the rule of thumb when doing pure FP is to avoid calling functions with the word "unsafe" in it unless you are really sure about what you are doing.

**Comment by clinuxrulz** [comment]
The function exists in both the Haskell version of Sodium as well as Reactive Banana.

**Comment by dakom** [comment]
What about `execute` for `Cell`?

**Comment by dakom** [comment]
I added execute - still need to add a test for it, and followup with turning it into a Typeclass if we need it for Cell too :)

Gotta head out - will be back in a day or two. :v:

**Comment by clinuxrulz** [comment]
Not that if the Typescript version ever changed from "push" to "push-pull", then that function would suddenly be required in the Typescript version too.

**Comment by clinuxrulz** [comment]
No execute for Cell.
