### ISSUE TITLE
Order of arguments

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/purescript-sodium#22]
I'm wondering if it would feel a little better to have the sodium objects come first, and have data / callbacks last.

See for example hold, accum, and snapshot. 

Note that the current approach of placing the sodium objects last, more closely follows the Haskell implementation.... and either approach can be made to work by using `flip` or whatever... but if we follow the idea of "most to least general" I'm not sure if the current approach is the best fit... 

thoughts?

**Comment by clinuxrulz** [comment]
I think keep haskell style or follow the of the haskell version of sodium.
We have ```(#)``` which is the reverse of ```($)``` to help us out syntactically if needed.

https://pursuit.purescript.org/packages/purescript-prelude/4.1.0/docs/Data.Function#v:(#)

```#``` sort of gives us the method looking style of calling that we see in OO languages.

**Comment by dakom** [comment]
ok cool - so functions first.

however, there's another issue which I think is just a mistake I made... for snapshot and lift, I followed the typescript implementation too literally, and it ends up with the _last_ argument provided, being the _first_ argument in the function.

For example:

```
lift3 :: forall a b c d cel. (SodiumCell cel) => (a -> b -> c -> d) -> cel b -> cel c -> cel a -> Cell d
```

should really be:

```
lift3 :: forall a b c d cel. (SodiumCell cel) => (a -> b -> c -> d) ->  cel a -> cel b -> cel c -> Cell d
```

i.e. the arguments in the function should match the cell arguments. I'll make a PR to get confirmation before merging

**Comment by dakom** [comment]
Note that the ramifactions of this change are that we can't partially apply it to wait for the target.

For example, this:

```
snapshot3 :: forall a b c d cel str. (SodiumStream str) => (SodiumCell cel) => (a -> b -> c -> d) -> cel b -> cel c -> str a -> Stream d
```

Will become this:

```
snapshot3 :: forall a b c d cel str. (SodiumStream str) => (SodiumCell cel) => (a -> b -> c -> d) -> str a -> cel b -> cel c -> Stream d
```

I don't think that's nearly as important as the argument order matching though - and one could always flip it around with a wrapper if they want, for partial application

**Comment by dakom** [comment]
Ah, yeah the proposed change is how it's done in Haskell:

```
snapshot :: (a -> b -> c) -> Event a -> Behavior b -> Event c
```

**Comment by dakom** [comment]
PR here: https://github.com/SodiumFRP/purescript-sodium/pull/23

**Comment by clinuxrulz** [comment]
Most the time you will not use ```lift``` in Purescript or Haskell. You would go ```yourFn <$> cA <*> cB <*> cC```. I.E. using the applicative functor interface.

You correct about the argument order change for lift.
