### ISSUE TITLE
Loopable typeclass

### ISSUE THREAD

**Issue by dakom** [SodiumFRP/purescript-sodium#7]

**Comment by clinuxrulz** [comment]
Recursive let expressions might be worth investigating.

**Comment by clinuxrulz** [comment]
One proposal:

```
class LoopSodiumObject target where
  loop :: forall a b. (target a -> Tuple (target a) b) -> Tuple (target a) b
```

A little big ugly, but helper methods can be derived using that typeclass for passing more sodium objects at once.

Since Purescript is eagar with no syntactic sugar for recursive do-notation you get backed into this corner. There are some cleaner solutions in Haskell. However under the hood you'll see a very similar type signature for ```fix``` and ```MonadFix``` in Haskell.

**Comment by dakom** [comment]
Interesting, thanks! I actually just spent the past hour or three trying to crack this, but couldn't figure it out :\ In other words, the following should hold true:

GOOD:
* loop Cell CellLoop
* loop Stream StreamLoop

BAD:
* loop Stream CellLoop
* loop Cell StreamLoop

NEUTRAL (but would probably fail, with easy resolution via the converter helpers):
* loop CellSink CellLoop
* loop StreamLoop StreamLoop

For now, I've pushed some work-in-progress stuff into the `wip` branch (didn't merge into master yet... among other reasons, ran into some newbie problems of not being able to call an empty constructor, so the build is currently failing - hope to fix tomm)

It just has distinct functions for `loop` in the `Cell` and `Stream` modules.... this isn't great since they'd need to be aliased on import for using both at the same time, and it would be wonderful if we could get it right via Typeclasses. 

Does your Tuple solution above solve this? Can't quite picture what you have in mind with the derived methods.

A related issue I was starting to tinker with but didn't commit is having Transaction callback be run not just in a plain `Effect`, but rather be some sort of encapsulation of an `Effect` so that we can enforce that `loop` must be called in a Transaction. Or do you think that's unnecessary to catch at the type level? (the JS will of course still scream at runtime)

**Comment by clinuxrulz** [comment]
I remember the Eff  monad. It could help us with its row polymorphism, insuring a loop only happens in a transaction (maybe). I'll have to have a play with your code again later to know for sure.

**Comment by clinuxrulz** [comment]
> It just has distinct functions for loop in the Cell and Stream modules.... this isn't great since they'd need to be aliased on import for using both at the same time, and it would be wonderful if we could get it right via Typeclasses.

I wouldn't be too worried about that. At some stage we'll need to simulate package-private causing us to create a sub ```Impl``` module, then reexport things through the parent module. It will give us the chance to restructure the modules how ever we want. A single ```SodiumFRP``` module where the end user can get at everything they need will probably be enough in the parent module.

**Comment by dakom** [comment]
Once we make everything available via parent module exports, won't we have a name clash between the two `loops`? Though I guess it's not terrible if we have `loopCell` and `loopStream` ?

**Comment by clinuxrulz** [comment]
In this definition (which may change for effects):
```
class LoopSodiumObject target where
  loop :: forall a b. (target a -> Tuple (target a) b) -> Tuple (target a) b
```
the ```target``` sodium object is polymorphic. Making it the same ```loop``` function for both ```Stream``` and ```Cell```. If I can get my hands on a computer tonight I'll show an example. Otherwise ```loopCell``` and ```loopStream``` is an alright short term solution.

**Comment by dakom** [comment]
Cool :)

Last night I made some major changes which allowed a more general SodiumCell / SodiumStream as input parameters to all primitives. Not sure if it helps in this case though.

Also there's an example in [Transaction.test.purs](https://github.com/SodiumFRP/purescript-sodium/blob/master/test/Transaction.test.purs) which uses the current `loop` from Cell and Stream... not so bad to need to alias it when using both at the same time in the same module, which I'd imagine is not very common...

**Comment by clinuxrulz** [comment]
Yes all of sodium is implemented via side effects under the hood. But not all off those effects are externally observable. It is done that way for performance sake.

**Comment by clinuxrulz** [comment]
```sample``` is a side effect.

**Comment by clinuxrulz** [comment]
I'll sweep over it soon, just a quick observation on my mobile.

**Comment by dakom** [comment]
So I spent a fair amount of time yesterday talking this out on the Purescript slack (great community btw) - and they told me that basically _anything_ from the FFI, that returns a new reference and isn't a constant, should be wrapped in an Effect.

I'm sure that's just generally good advice since JS is unsafe, but it may not apply here - and fwiw I'm very happy to change it back... I did sneak it in via `mempty` for the Stream Monoid and I was quietly wondering if that will be a problem :)

Though what about the `Sink` and `Loop` versions... I'd imagine those _should_ be in Effect since they're not referentially transparent? In other words, if they're defined as `:: Unit -> Sink` and Purescript tries to be smart and re-use an existing sink when given a `unit`, we're in trouble..?

Tbh I'm still trying to wrap my head around what an Effect _is_, and how it relates to FFI... corrections and insight on anything is appreciated, as always :)

(re: Cell and Applicative - yeah, for sure... hoping to finish Cell and maybe Operational tonight... should be smooth sailing since it's mostly just repeating what's there)

**Comment by dakom** [comment]
Actually re: Loop as discussed elsewhere, that shouldn't only be in Effect, I think it should be in a special Transaction Effect so we can catch the "must be declared in a Transaction" at the type level...

**Comment by clinuxrulz** [comment]
Even ```new Tuple(1,2);``` returns a new reference each time it is called, but is still considered the same value. And is still considered a pure operation. The trick is pure functional languages do not let you compare by reference.

**Comment by clinuxrulz** [comment]
```loop``` can be considered an effect because a different thing happens when executed outside of a transaction.

**Comment by clinuxrulz** [comment]
Sink construction is an effect. Because the push/send method will be wired to a particular sodium object.

**Comment by dakom** [comment]
right on - just to understand better, using your Tuple example...

Exchanging one instance of `new Tuple(1,2)` with another `new Tuple(1,2)`, in a language that only allows pure functions - shouldn't make any difference to the resulting code since it's only the values that matter.

for example, if we pass it to pure functions like `add`, it doesn't matter which instances they are, since adding any two `Tuple (1,2)` will give us a `Tuple(2,4)`

However... when we consider this same concept with each of:

* CellLoop / StreamLoop
- it's a problem since `loop` mutates the object. Additionally it _must_ happen in a transaction so its inherently bound to an Effect of some sort.

* CellSink / StreamSink
- it's a problem since `send` is bound to a specific object (hah - was writing this when you said nearly the same exact thing!)

* Cell/Stream
- actually not a problem, since all Cells/Streams that were created with particular values can be replaced with any others of the same values and everything is fine

?

**Comment by clinuxrulz** [comment]
Yes correct! ... And sorry man, I'm going to have to break my promise of jumping on a computer tonight. Feeling a bit tired at the moment. I'll leave it in your capable hands.

**Comment by dakom** [comment]
Yay! Feels good to learn something :)

My hands are getting more capable thanks to your help, I really appreciate it!

Have a good rest. I probably will give it another go tonight unless I'm tired then too, hehe. Most likely I won't change the Loop stuff but rather some of the other to-do's. ✌️

**Comment by clinuxrulz** [comment]
https://github.com/SodiumFRP/sodium/blob/master/haskell/src/FRP/Sodium/Context.hs might be a good guide, just visualize Reactive monad as the effect monad.

Cheers, good night.

**Comment by clinuxrulz** [comment]
Just having a quick glance again. ```loopCell```, ```loopStream``` being separate names would be fine.

Last time I was thinking recursive-do without the syntactic sugar. Your way seems tidy.
